PipelineSecrets: {}
btcd-kube:
  project:
    namespace: lightning-kube-mainnet
    network: mainnet
    networkSuffix: -mainnet
    storage: 275Gi
  service:
    http:
      externalPort: 8333
      internalPort: 8333
    rpc:
      externalPort: 8334
      internalPort: 8334
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
controllerbuild: {}
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 35.225.224.89.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global: {}
project:
  namespace: btcd-kube
  network: mainnet
  networkSuffix: -mainnet
prow: {}
